FROM teradatalabs/centos6-java8-oracle
MAINTAINER Grzegorz Kokosiński <grzegorz.kokosinksi@teradata.com>

RUN curl -SL http://search.maven.org/remotecontent?filepath=io/prestosql/presto-cli/302/presto-cli-302-executable.jar -o presto-cli.jar

