FROM prestodev/centos6-oj8
MAINTAINER Presto community <https://prestosql.io/community.html>

RUN curl -SL http://search.maven.org/remotecontent?filepath=io/prestosql/presto-cli/302/presto-cli-302-executable.jar -o presto-cli.jar

