DOCKER_MACHINE: localhost

cluster:
  trino: ${DOCKER_MACHINE}
  cassandra: ${DOCKER_MACHINE}
  hadoop: ${DOCKER_MACHINE}
  psql1: ${DOCKER_MACHINE}
  psql2: ${DOCKER_MACHINE}
  ssh: ${DOCKER_MACHINE}

hdfs:
  username: hdfs
  webhdfs:
    uri: http://${cluster.hadoop}:50070

psql1:
  port: 15432
psql2:
  port: 15433

databases:
  default:
    alias: trino

  hive:
    jdbc_driver_class: org.apache.hive.jdbc.HiveDriver
    jdbc_url: jdbc:hive2://${cluster.hadoop}:10000
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    table_manager_type: hive
    inject_stats_for_immutable_tables: true
    inject_stats_for_mutable_tables: true
    metastore:
      host: ${cluster.hadoop}
      port: 9083

  trino:
    jdbc_driver_class: io.trino.jdbc.TrinoDriver
    jdbc_url: jdbc:trino://${cluster.trino}:8080/hive/default
    jdbc_user: hdfs
    jdbc_pooling: false
    table_manager_type: jdbc

  trino_tpcds:
    jdbc_driver_class: io.trino.jdbc.TrinoDriver
    jdbc_url: jdbc:trino://${cluster.trino}:8080/hive/tpcds
    jdbc_user: hdfs
    jdbc_pooling: false

  psql:
    jdbc_driver_class: org.postgresql.Driver
    jdbc_url: jdbc:postgresql://${cluster.psql1}:${psql1.port}/postgres
    jdbc_user: blah
    jdbc_password: blah
    jdbc_pooling: true
    table_manager_type: jdbc

  psql2:
    jdbc_driver_class: org.postgresql.Driver
    jdbc_url: jdbc:postgresql://${cluster.psql2}:${psql2.port}/postgres
    jdbc_user: blah
    jdbc_password: blah
    jdbc_pooling: true
    table_manager_type: jdbc

  cassandra:
    host: ${cluster.cassandra}
    port: 9042
    local_datacenter: datacenter1
    default_schema: test
    skip_create_schema: false
    table_manager_type: cassandra

  kafka:
    broker:
      host: kafka
      port: 9092
    zookeeper:
      host: kafka
      port: 2181
    table_manager_type: kafka

tests:
  hdfs:
    path: /tempto

ssh:
  identity: ${IDENTITY}
  roles:
    host_by_password:
      host: ${cluster.ssh}
      port: 22
      user: ${USER_A}
      password: ${USER_A_PASSWORD}

    host_by_identity:
      host: ${cluster.ssh}
      port: 22
      user: ${USER_B}

list:
  string:
    - ala
    - ma
    - kota

command:
  suite:
    - echo first configuraiton suite command output
    - echo second configuraiton suite command output
    - touch configuratioCommandTestFile
  test:
    - echo first configuraiton test command output
    - echo second configuraiton test command output
